### ISSUE TITLE
小白关于数据集的一些问题，望解答

### ISSUE THREAD

**Issue by Hui-zju** [miracleyoo/pytorch-lightning-template#3]
1、这里验证集和测试集是一样的？如果一样，又使用了EarlyStopping，模型不就没有说服力了吗？
`    def setup(self, stage=None):
        # Assign train/val datasets for use in dataloaders
        if stage == 'fit' or stage is None:
            self.trainset = self.instancialize(train=True)
            self.valset = self.instancialize(train=False)

        # Assign test dataset for use in dataloader(s)
        if stage == 'test' or stage is None:
            self.testset = self.instancialize(train=False)`

2、这里self.train是没定义，还是能从别的地方继承来？
`self.path_list = fl_train if self.train else fl_val`

**Comment by Hui-zju** [comment]
第2个问题好像找打答案了，应该是这一句：self.__dict__.update(locals())

**Comment by miracleyoo** [comment]
对 第一个问题就像你说的这样。因为不是所有任务都会有测试集的，为了方便develope，这里把测试集测的内容设置为了和验证集一样，如果你有独立测试集，按照验证集的写法改成你的测试集内容即可。
