### ISSUE TITLE
RuntimeError: Please only pass an ArgumentParser instance.

### ISSUE THREAD

**Issue by 1s23** [miracleyoo/pytorch-lightning-template#4]
你好，请问这个怎么解决啊？
![截图_20213201113240](https://user-images.githubusercontent.com/52626440/131607471-97dfb1a4-bf40-4857-8fef-d32b83c54eb2.png)
![截图_20213201113253](https://user-images.githubusercontent.com/52626440/131607473-6d8f385e-d064-478e-9940-a30aeccfa717.png)

**Comment by jlxy** [comment]
遇到了同样的问题，请问楼主解决了吗？

**Comment by samleoqh** [comment]
> 改成这样，就没问题了
 
   parser.add_argument_group(title="pl.Trainer args")
    parser = Trainer.add_argparse_args(parser)
